efficient MCTS
opendilab/LightZero pull request #136
Opened 2023-11-04 13:55 UTC by HarryXuancy

code are submitted for discussion

2023-11-27 11:59 UTC, puyuan1996 commented on lzero/mcts/buffer/game_buffer_ma.py
> +            if self._cfg.mcts_ctree:
def compute_all_filters(data, num_unroll_steps):
    data_by_iter = []
    for iter in range(num_unroll_steps + 1):
        iter_data = [x for i, x in enumerate(data)
                     if (i + 1) % (num_unroll_steps + 1) ==
                     ((num_unroll_steps + 1 - iter) % (num_unroll_steps + 1))]
        data_by_iter.append(iter_data)
    return data_by_iter

if self._cfg.mcts_ctree:
    legal_actions_by_iter = compute_all_filters(legal_actions, self._cfg.num_unroll_steps)
    noises_by_iter = compute_all_filters(noises, self._cfg.num_unroll_steps)
    reward_pool_by_iter = compute_all_filters(reward_pool, self._cfg.num_unroll_steps)
    policy_logits_pool_by_iter = compute_all_filters(policy_logits_pool, self._cfg.num_unroll_steps)
    to_play_by_iter = compute_all_filters(to_play, self._cfg.num_unroll_steps)
    latent_state_roots_by_iter = compute_all_filters(latent_state_roots, self._cfg.num_unroll_steps)
    true_action_by_iter = compute_all_filters(true_action, self._cfg.num_unroll_steps)

    temp_values = []
    temp_distributions = []
    mcts_ctree = MCTSCtree(self._cfg)

    for iter in range(self._cfg.num_unroll_steps + 1):
        iter_batch_size = transition_batch_size / (self._cfg.num_unroll_steps + 1)
        roots = MCTSCtree.roots(iter_batch_size, legal_actions_by_iter[iter])

        roots.prepare(self._cfg.root_noise_weight, 
                      noises_by_iter[iter], 
                      reward_pool_by_iter[iter],
                      policy_logits_pool_by_iter[iter], 
                      to_play_by_iter[iter])

        if iter == 0:
            mcts_ctree.search(roots, model, latent_state_roots_by_iter[iter], to_play_by_iter[iter])
        else:
            mcts_ctree.search_with_reuse(roots, model, latent_state_roots_by_iter[iter], 
                                         to_play_by_iter[iter],
                                         true_action_list=true_action_by_iter[iter], 
                                         reuse_value_list=iter_values)

        iter_values = roots.get_values()
        iter_distributions = roots.get_distributions()
        temp_values.append(iter_values)
        temp_distributions.append(iter_distributions)

2024-04-18 12:54 UTC, puyuan1996 requested changes

2024-04-18 12:54 UTC, puyuan1996 commented on lzero/entry/__init__.py
> +from .train_muzero_with_gym_env import train_muzero_with_gym_env
不同的entry都尽可能整合到train_muzero.py中，通过传入一个option来选择具体的不同处理方式。与train_muzero.py差别很大的才单独新建文件。尽可能保持代码的整洁和可维护性。

2024-04-18 12:54 UTC, puyuan1996 commented on lzero/mcts/buffer/game_buffer.py
> +    def _sample_orig_reanalyze_data(self, batch_size: int) -> Tuple:
这个新增方法的目的是？

2024-04-18 12:54 UTC, puyuan1996 commented on lzero/mcts/buffer/game_buffer.py
> +            # weights_list /= weights_list.max()
把目前用不到的注释可以删除了哈，如果是TODO需要后续check的写清楚注释

2024-04-18 12:54 UTC, puyuan1996 commented on lzero/mcts/buffer/game_buffer_ma.py
> +from typing import Any, List, Tuple, Union, TYPE_CHECKING, Optional
game_buffer也类似，通过继承之前的game_buffer，只增加最必须的方法，其他的尽可能复用哈，不需要的中文注释删除了，必要的可以转变成扼要的英文注释哈

2024-04-18 12:54 UTC, puyuan1996 commented on lzero/mcts/ctree/ctree_efficientzero/lib/cnode.cpp
> +            Expand the nodes along the search path and update the infos.
ctree中增加的方法，注释也对应修改一下哈

2024-04-18 12:54 UTC, puyuan1996 commented on lzero/mcts/ptree/ptree_mz.py
> +        true_reward = child.reward
ptree中也是哈，注释修改一下。对了目前rezero的代码都是用ctree跑的吧，ptree是最开始为了原理调试写的吧

2024-04-18 12:54 UTC, puyuan1996 commented on lzero/mcts/tree_search/mcts_ctree.py
> +            Do MCTS for the roots (a batch of root nodes in parallel). Parallel in model inference.
更新注释

2024-04-18 12:54 UTC, puyuan1996 commented on lzero/policy/ma.py
> +    Overview:
改成继承自muzero，并重新命名为 rezero ，只增加修改后的方法哈，尽可能保持代码整洁易懂

2024-04-18 12:54 UTC, puyuan1996 commented on lzero/worker/ma_collector.py
> +        The Collector for MCTS+RL algorithms, including MuZero, EfficientZero, Sampled EfficientZero, Gumbel MuZero.
同样的命名，注释等改写一下，继承自muzero_collector

2024-04-18 12:54 UTC, puyuan1996 commented on zoo/atari/config/main_config/pong_mcma.py
> +
atari的所有config，对于一个算法，不同环境公用同一个config，里面用分支选择特定的参数，config对应的算法命名改一下。

2024-04-19 05:12 UTC, HarryXuancy commented on Untitled Diagram.drawio
> +<mxfile host="app.diagrams.net" modified="2024-01-24T07:16:11.105Z" agent="Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0" version="21.8.2" etag="4qZMPrcOvV_-34SzBdEL" t
好的这个我删除一下

2024-04-19 05:13 UTC, HarryXuancy commented on lzero/mcts/buffer/game_buffer.py
> +    def _sample_orig_reanalyze_data(self, batch_size: int) -> Tuple:
这个应该是在做buffer reanalyze的时候切分buffer用的，因为reanalyze的时候是2000个样本做一个batch一起搜索，所以要通过sample把样本组织成一个个batch，这一块的方法我后续可能再优化一下

2024-04-19 05:15 UTC, HarryXuancy commented on lzero/mcts/ptree/ptree_mz.py
> +        true_reward = child.reward
是的，ptree当时改了一半，再后来就没有调试过了，暂时还没有更新ptree版本的代码，这些注释我删一下

2024-05-08 03:38 UTC, puyuan1996 commented on lzero/entry/train_nrma.py
> +        input_cfg: Tuple[dict, dict],
这个函数名改成更详细一点的吧，希望能见名知意。

2024-05-08 03:38 UTC, puyuan1996 commented on lzero/entry/train_nrma.py
> +    """
改一下注释

2024-05-08 03:38 UTC, puyuan1996 commented on lzero/entry/train_nrma.py
> +                    # policy对sample的影响是什么？？？？？？？？？？？？？？？？？？？？？？？？？
多余注释删了，必要的注释和TODO，用英文简要地写一下？

2024-05-08 03:38 UTC, puyuan1996 commented on zoo/atari/config/main_config/asterix_ma.py
> +from easydict import EasyDict
类似这样 https://github.com/opendilab/LightZero/blob/dev-unizero/zoo/atari/config/atari_unizero_config_stack1_atari20games.py 将atari的各个算法的config都整合一下，每个算法只需要一个config即可

2024-05-08 03:38 UTC, puyuan1996 commented on lzero/worker/ma_collector.py
> +                    # else:
注释整合修改

2024-05-08 03:38 UTC, puyuan1996 commented on lzero/mcts/buffer/game_buffer_nrma.py
> +        The specific game buffer for MuZero policy.
命名和注释改一下吧。nrma读者很难知道具体的功能

2024-05-08 03:38 UTC, puyuan1996 commented on lzero/mcts/buffer/game_buffer_rezeroe.py
> +@BUFFER_REGISTRY.register('game_buffer_rezeroe')
或许改成game_buffer_rezero_ez更加清晰一些哈

2024-06-24 12:12 UTC, closed without merging

2024-06-24 12:12 UTC, puyuan1996 commented
We have a new polished PR https://github.com/opendilab/LightZero/pull/238.