feature(rjy): add mtcar env and muzero visualization
opendilab/LightZero pull request #181
Opened 2024-01-11 04:02 UTC by nighood

2024-01-12 08:22 UTC, puyuan1996 commented
增加这个PR功能的 description，以及把可视化相关代码也提交上来吧。代码需要增加详细规则的注释，请参考lunarlander的环境。

2024-01-12 08:23 UTC, puyuan1996 commented
目前mtcar muzero的性能是如何的呢

2024-01-29 10:44 UTC, puyuan1996 commented on zoo/classic_control/mountain_car/entry/mountain_car_eval.py
> +from zoo.classic_control.mountain_car.config.mtcar_muzero_config import main_config, create_config
3个ipynb各自的不同，主要功能在开始写清楚哈，可以先中文，但是后面需要转成英文版本的哈

2024-01-29 10:44 UTC, puyuan1996 commented on zoo/classic_control/mountain_car/config/mtcar_muzero_config.py
> +    train_muzero([main_config, create_config], seed=0, max_env_step=max_env_step)
把train_muzero_with_gym_env相关的先去掉哈，暂时用不到

2024-01-29 10:45 UTC, puyuan1996 commented
> 目前mtcar muzero的性能是如何的呢

把目前的基线结果及其相关介绍放在上面的description里面哈

2024-02-05 09:44 UTC, puyuan1996 requested changes

2024-02-05 09:44 UTC, puyuan1996 commented on zoo/classic_control/mountain_car/config/mtcar_muzero_config.py
> +    exp_name=f'lz_result/debug/mountain_car_muzero_ns{num_simulations}_upc{update_per_collect}_rr{reanalyze_ratio}_seed0',
exp_name按照我们已有config的格式，去掉 lz_result/debug/ 这个前缀

2024-02-05 09:44 UTC, puyuan1996 commented on zoo/classic_control/mountain_car/entry/mountain_car_eval.py
> +    print("=" * 20)
目前只保留zoo/classic_control/mountain_car/entry/vis_mz_mtcar.ipynb这个吧，命名中vis换成完整的 visualize，以及文件中注明参考的论文和链接，写一下整体的介绍

2024-02-05 09:44 UTC, puyuan1996 commented on lzero/worker/muzero_evaluator.py
>          Overview:
关于添加的episode_info['trajectory']，注释中增加相应的说明

2024-02-05 09:44 UTC, puyuan1996 commented on zoo/classic_control/mountain_car/envs/mtcar_lightzero_env.py
> +        # action = action.squeeze()
无用的注释删除了

2024-02-19 07:50 UTC, puyuan1996 requested changes

2024-02-19 07:50 UTC, puyuan1996 commented on zoo/classic_control/mountain_car/config/mtcar_muzero_config.py
> +    # Users can use different train entry by specifying the entry_type.
无用的注释删除了

2024-02-19 07:54 UTC, puyuan1996 commented on lzero/worker/muzero_evaluator.py
> +            episode_info['trajectory'] = game_segments
返回的game_segments是完整的几局轨迹吗？

2024-02-19 08:00 UTC, puyuan1996 commented on zoo/classic_control/mountain_car/envs/mtcar_lightzero_env.py
> +    > LightZero's env creation conventions : https://is.gd/ZHLISj
需要写一下 
- 任务的整体介绍
- obs action reward episode_length_limit 等MDP信息的详细注释，

2024-02-26 08:32 UTC, puyuan1996 commented on zoo/classic_control/mountain_car/config/mtcar_muzero_config.py
> +    # Users can use different train entry by specifying the entry_type.
- 目前有到-110说明是能够达到终点的，需要看看目前设置下后期性能不稳定的原因，分析一下collect/eval/learn tb，梯度norm，输出policy logits等的变化情况。
- 可能的测试config: 
  - reanalyze_ratio = 1
  - grad_clip_value=0.5

2024-02-26 14:58 UTC, nighood commented on lzero/worker/muzero_evaluator.py
> +            episode_info['trajectory'] = game_segments
一局

2024-03-19 07:39 UTC, nighood commented on zoo/classic_control/mountain_car/envs/mtcar_lightzero_env.py
> +    > LightZero's env creation conventions : https://is.gd/ZHLISj
我直接加mountain_car的gym链接在ipynb可以吗
https://www.gymlibrary.dev/environments/classic_control/mountain_car/

2024-03-19 12:59 UTC, merged