save the search results to buffer during reanalyze
opendilab/LightZero pull request #190
Opened 2024-03-01 08:01 UTC by HarryXuancy

1. save the searched visit counts and root values to buffer during reanalyze
2. fix some typos in comments

2024-03-01 10:29 UTC, puyuan1996 requested changes

2024-03-01 10:29 UTC, puyuan1996 commented on lzero/mcts/buffer/game_buffer_efficientzero.py
> +            # noises are not necessary for reanalyze
那可以把产生noise相关的代码删除了哈。之前验证过不加noise对性能的影响吗？

2024-03-01 10:29 UTC, puyuan1996 commented on lzero/mcts/buffer/game_buffer_efficientzero.py
> +                            # update the data in game segment
关于把search results放回buffer中的原理和目的在这里介绍清楚吧

2024-03-01 10:29 UTC, puyuan1996 commented on lzero/mcts/buffer/game_buffer_efficientzero.py
> +                            # print(f'the visit in index{current_index} is {child_visit[current_index]}')
调试代码可以删除了哈

2024-03-08 13:21 UTC, HarryXuancy commented on lzero/mcts/buffer/game_buffer_efficientzero.py
> +            # noises are not necessary for reanalyze
没有单独验证过，确实应该验证一下

2024-03-11 03:32 UTC, puyuan1996 commented on zoo/atari/config/mspacman_config_ez.py
> +
这个config是错误传上来的吧，删除一下

2024-03-13 06:52 UTC, merged