feature(xcy): add ReZero algo. and related configs
opendilab/LightZero pull request #238
Opened 2024-06-24 12:11 UTC by puyuan1996

- Our arxiv paper is on [ReZero: Boosting MCTS-based Algorithms by Backward-view and Entire-buffer Reanalyze](https://arxiv.org/abs/2404.16364).

2024-06-25 13:16 UTC, PaParaZz1 requested changes

2024-06-25 13:16 UTC, PaParaZz1 commented on lzero/entry/utils.py
> +        # Reset the time records in the buffer.
this reset method should be set in buffer and called by outside

2024-06-25 13:16 UTC, PaParaZz1 commented on lzero/entry/utils.py
> +    Note:
.. note::

2024-06-25 13:16 UTC, PaParaZz1 commented on lzero/mcts/buffer/game_segment.py
> +        if sum_visits == 0:
add comments for this branch

2024-06-27 12:16 UTC, puyuan1996 commented on zoo/atari/config/atari_rezero_ez_config.py
> +        reanalyze_ratio=0,  # NOTE: for rezero, reanalyze_ratio should be 0. To be compatible with muzero.
ReZero是通过buffer_reanalyze_freq控制reanalyze频率的，这个参数用不到，但为了与muzero兼容，保留它为默认值。

2024-06-28 03:51 UTC, merged