feature(wrh): Add Harmony Dream in Muzero
opendilab/LightZero pull request #242
Opened 2024-07-08 02:19 UTC by ruiheng123

2024-07-08 04:17 UTC, puyuan1996 requested changes

2024-07-08 04:17 UTC, puyuan1996 commented on lzero/model/muzero_model.py
> +            self.harmony_s1 = nn.Parameter(-torch.log(torch.tensor(1.0)))
这里初始化为为-torch.log(torch.tensor(1.0))，有什么特别的原因呢？为什么要加上负号呢？可以提个issue询问一下

2024-07-08 04:17 UTC, puyuan1996 commented on lzero/policy/muzero.py
> +        # ==============================================================
或许可以将 `use_harmony` 换成 `harmony_balance`, 并在muzero上方的默认config中加上harmony_balance 的默认为False，以及相关的注释

2024-07-08 04:17 UTC, puyuan1996 commented on lzero/model/muzero_model.py
> +            self.harmony_s5 = nn.Parameter(-torch.log(torch.tensor(1.0)))
s1-5换成对应loss的name简写，例如 harmony_latent, harmony_policy, harmony_value, harmony_reward, harmony_entropy

2024-07-08 04:17 UTC, puyuan1996 commented on lzero/model/muzero_model.py
> +            self.harmony_s5 = nn.Parameter(-torch.log(torch.tensor(1.0)))
可以类似下面这样写，方便扩展哈
```python
            # List of parameter names
            harmony_names = ["harmony_latent", "harmony_policy", "harmony_value", "harmony_reward", "harmony_entropy"]
            
            # Initialize and name each parameter
            for name in harmony_names:
                param = nn.Parameter(-torch.log(torch.tensor(1.0)))
                setattr(self, name, param)
```

2024-07-08 04:17 UTC, puyuan1996 commented on lzero/model/muzero_model.py
> +            self.harmony_s5 = nn.Parameter(-torch.log(torch.tensor(1.0)))
另外，这里的相关定义，应该移动到 muzero policy 的 _init_learn 中去哈，这样就可以避免下面这样的冗余代码，`self.harmony_s1 = self._model.harmony_s1`

2024-07-08 04:27 UTC, ruiheng123 commented on lzero/model/muzero_model.py
> +            self.harmony_s1 = nn.Parameter(-torch.log(torch.tensor(1.0)))
![图片](https://github.com/opendilab/LightZero/assets/121342992/71b5400f-59ed-44e9-b5e6-89288cbad84e)
参照的原官方代码

2024-07-15 12:09 UTC, puyuan1996 requested changes

2024-07-15 12:09 UTC, puyuan1996 commented on zoo/atari/config/atari_muzero_config.py
> +            harmony_balance=False # Referred as https://github.com/thuml/HarmonyDream.
muzero默认是Flase，这里可以删除了哈

2024-07-15 12:09 UTC, puyuan1996 commented on lzero/policy/muzero.py
> +                # torch.log(torch.exp(self.harmony_entropy) + 1)
把549，553，557行的harmony_dynamics和harmony_entropy相关的注释删除一下

2024-07-15 12:09 UTC, puyuan1996 commented on lzero/policy/muzero.py
> +            harmony_balance=False
增加HarmonyDream论文的参考，例如 More details can be found in <>.

2024-07-15 12:09 UTC, puyuan1996 commented on lzero/policy/muzero.py
> +        # Referred as https://github.com/thuml/HarmonyDream/blob/main/wmlib-torch/wmlib/agents/dreamerv2.py#L161
这行修改为：Please refer to *

2024-07-16 03:11 UTC, merged