feature(pu): add rope that use the true timestep index as pos_index
opendilab/LightZero pull request #266
Opened 2024-08-15 11:08 UTC by puyuan1996

-  add rope that use the true timestep index as pos_index in unizero's transformer

2025-03-27 07:06 UTC, PaParaZz1 requested changes

2025-03-27 07:06 UTC, PaParaZz1 commented on lzero/model/unizero_world_models/world_model.py
> +        if self.config.rotary_emb:
remove these two lines since if is not necessary

2025-03-27 07:06 UTC, PaParaZz1 commented on lzero/model/unizero_world_models/world_model.py
> +            return_result += self.pos_emb(prev_steps + torch.arange(num_steps, device=self.device))
you don't need to add this if branch here

2025-03-27 07:06 UTC, PaParaZz1 commented on lzero/model/unizero_world_models/world_model.py
> +                # TODO: 记录从root node开始，位于树中的深度，以判断rope的位置编码索引
English TODO comments

2025-03-27 07:06 UTC, PaParaZz1 commented on lzero/model/unizero_world_models/world_model.py
> +            search_depth=[]
why set empty here

2025-03-29 15:19 UTC, puyuan1996 commented on lzero/model/unizero_world_models/transformer.py
> +            if isinstance(start_pos, int) or isinstance(start_pos, float):
We have simplified and refined the process of start_pos.

2025-03-29 15:32 UTC, puyuan1996 commented on lzero/policy/unizero.py
> +        reanalyze_ratio=0,
deleted now, `reanalyze_ratio` is in `replay_buffer`'s default config.

2025-03-29 15:33 UTC, puyuan1996 commented on lzero/policy/unizero.py
> +        obs_batch_ori, action_batch,  target_action_batch, mask_batch, indices, weights, make_time, batch_timestep = current_batch
polished now

2025-03-29 16:00 UTC, puyuan1996 commented on lzero/model/unizero_world_models/world_model.py
> +        if self.config.rotary_emb:
polished

2025-03-29 16:04 UTC, puyuan1996 commented on lzero/model/unizero_world_models/world_model.py
> +            search_depth=[]
search_depth is not used in this method, polished now.

2025-03-29 16:17 UTC, puyuan1996 commented on lzero/model/unizero_world_models/world_model.py
> +            return_result += self.pos_emb(prev_steps + torch.arange(num_steps, device=self.device))
The polishing of pos_emb will be addressed in a future PR.

2025-03-29 16:52 UTC, merged