feature(zt): add stochastic muzero
opendilab/LightZero pull request #45
Opened 2023-06-10 09:01 UTC by timothijoe

add mcts ptree and ctree into muzero
add atari config

2023-06-10 14:23 UTC, PaParaZz1 requested changes

2023-06-12 04:37 UTC, puyuan1996 requested changes

2023-06-12 04:37 UTC, puyuan1996 commented on lzero/policy/stochastic_muzero.py
> +        The policy class for MuZero.
更改算法名称

2023-06-12 04:37 UTC, puyuan1996 commented on lzero/policy/stochastic_muzero.py
> +
`bash format.sh lzero/policy` 格式化代码

2023-06-12 04:37 UTC, puyuan1996 commented on lzero/policy/stochastic_muzero.py
> +        obs_batch_ori, action_batch, mask_batch, indices, weights, make_time = current_batch
` obs_batch_ori` 更改为 `obs_batch_orig`

2023-06-12 04:37 UTC, puyuan1996 commented on lzero/policy/stochastic_muzero.py
> +        for zt in range(5):
`zt` -> `i`
5 -> config中的参数

2023-06-12 04:37 UTC, puyuan1996 commented on lzero/policy/stochastic_muzero.py
> +            network_output = self._learn_model.recurrent_inference(latent_state, action_batch[:, step_i], afterstate=False)
注释给出参数afterstate的含义

2023-06-12 04:37 UTC, puyuan1996 commented on lzero/policy/stochastic_muzero.py
> +            chance_code_long = torch.argmax(chance_code, dim=1).long().unsqueeze(-1)
为什么必须是long类型的？

2023-06-12 04:37 UTC, puyuan1996 commented on lzero/policy/stochastic_muzero.py
> +            after_state, a_reward, a_value, a_policy_logits = mz_network_output_unpack(network_output)
`a_reward` -> `afterstate_reward,` 其他变量类似修改，更加清晰

2023-06-12 04:37 UTC, puyuan1996 commented on lzero/policy/stochastic_muzero.py
> +            + self._cfg.policy_loss_weight * commitment_loss
` afterstate_policy_loss`, `afterstate_value_loss`, `commitment_loss`应该有自己的weight，与原文对齐

2023-06-12 04:37 UTC, puyuan1996 commented on zoo/atari/config/atari_stochastic_muzero.py
> +from easydict import EasyDict
rename to `atari_stochastic_muzero_config.py`

2023-06-12 04:37 UTC, puyuan1996 commented on zoo/atari/config/atari_stochastic_muzero.py
> +from easydict import EasyDict
增加2048相关环境和config，以及cartpole/lunarlander的相关stochastic_muzero_config

2023-06-12 04:37 UTC, puyuan1996 commented on zoo/atari/config/atari_stochastic_muzero.py
> +        num_simulations=num_simulations,
`optim_type='SGD', 
        lr_piecewise_constant_decay=True,
        learning_rate=0.2,`
修改为
 `optim_type='AdamW',
        lr_piecewise_constant_decay=False,
        learning_rate=0.003,`
下面这组参数在几乎所有测试环境上效果都不错。

2023-06-16 04:01 UTC, puyuan1996 requested changes

2023-06-16 04:01 UTC, puyuan1996 commented on lzero/model/stochastic_muzero_model.py
> +class StraightThroughEstimator(nn.Module):
这里的代码你是参考的哪里的吗？需要写单元测试，验证原理的正确性

2023-06-16 04:01 UTC, puyuan1996 commented on zoo/game_2048/envs/game_2048_env.py
> +class Game2048Env(gym.Env):
增加overview, 注释按之前的标准写。

2023-06-16 04:01 UTC, puyuan1996 commented on zoo/game_2048/envs/game_2048_env.py
> +from __future__ import print_function
这个是不必要的吧

2023-08-08 18:08 UTC, puyuan1996 commented
We have a new polished [PR](https://github.com/opendilab/LightZero/pull/64).

2023-08-08 18:08 UTC, closed without merging