doc(lxy): add gumbel muzero to readme
opendilab/LightZero pull request #46
Opened 2023-06-16 04:52 UTC by karroyan

2023-06-16 09:53 UTC, PaParaZz1 requested changes

2023-06-16 09:53 UTC, PaParaZz1 commented on README.md
>  - [MuZero](https://arxiv.org/abs/1911.08265)
you need to also add these information in Chinese readme

2023-06-16 09:53 UTC, PaParaZz1 commented on README.md
> +| pendulum      | ---       | ✔    | ✔           | ✔                   | 🔒             |
add repo `mctx` in Acknowledgments

2023-06-16 09:53 UTC, PaParaZz1 commented on README.md
add some benchmark results about gumbel muzero

2023-06-21 03:19 UTC, puyuan1996 requested changes

2023-06-21 03:19 UTC, puyuan1996 commented on README.md
> +| bipedalwalker   | ---       | ✔    | ✔           | ✔                   | 🔒             |
It would be a good idea to add bipedalwalker and pendulum gumbel related config

2023-06-21 03:19 UTC, puyuan1996 commented on README.md
> +  <img src="assets/benchmark/ablation/lunarlander_gmz_ns.png" alt="Image Description 3" width="23%" height="auto" style="margin: 0 1%;">
It appears that the Gumbel benchmark image was not uploaded correctly. Consider using a command like 
`git add -f assets/benchmark/ablation/pong_gmz_ns.png ` to force the addition of the image.

2023-06-21 03:19 UTC, puyuan1996 commented on README.md
> +- [GumbelMuZero](https://github.com/opendilab/LightZero/blob/main/assets/paper_notes/GumbelMuZero.pdf)
GumbelMuZero paper notes is not uploaded correctly.

2023-06-26 05:05 UTC, merged