feature(yzj): add eps greedy and random collect option
opendilab/LightZero pull request #54
Opened 2023-07-17 09:13 UTC by jayyoung0802

2023-07-17 10:14 UTC, puyuan1996 requested changes

2023-07-17 10:14 UTC, puyuan1996 commented on lzero/entry/train_muzero.py
> +        collect_kwargs['epsilon'] = 0.0
这3行可以改为一行

2023-07-17 10:14 UTC, puyuan1996 commented on lzero/policy/efficientzero.py
>          ready_env_id=None
=前后加上空格

2023-07-17 10:14 UTC, puyuan1996 commented on lzero/policy/efficientzero.py
> +                    # action = np.where(action_mask[i] == 1.0)[0][action_index_in_legal_action_set]
没有用到的这一行可以删除了

2023-07-17 10:14 UTC, puyuan1996 commented on lzero/policy/efficientzero.py
> +                    if self._cfg.eps.eps_greedy_exploration_in_collect:
加上类似这样的注释 # if normal collect phase

2023-07-17 10:14 UTC, puyuan1996 commented on lzero/policy/efficientzero.py
> +                if random_collect_episode_num>0:  # random collect
> 前后空格，yapf format
注释写在if语句下面，并简介其含义与用途

2023-07-17 10:14 UTC, puyuan1996 commented on lzero/policy/muzero.py
> +                    action_index_in_legal_action_set, visit_count_distribution_entropy = select_action(
类似上面的修改

2023-07-17 10:14 UTC, puyuan1996 commented on zoo/atari/config/atari_efficientzero_config.py
> +random_collect_episode_num=0
在muzero efficientzero policy中增加对应的默认config和注释说明

2023-07-17 11:47 UTC, jayyoung0802 commented on lzero/entry/train_muzero.py
> +        collect_kwargs['epsilon'] = 0.0
done

2023-07-17 11:47 UTC, jayyoung0802 commented on lzero/policy/efficientzero.py
>          ready_env_id=None
done

2023-07-17 11:47 UTC, jayyoung0802 commented on lzero/policy/efficientzero.py
> +                    # action = np.where(action_mask[i] == 1.0)[0][action_index_in_legal_action_set]
done

2023-07-17 11:48 UTC, jayyoung0802 commented on lzero/policy/efficientzero.py
> +                    if self._cfg.eps.eps_greedy_exploration_in_collect:
done

2023-07-17 11:50 UTC, jayyoung0802 commented on lzero/policy/efficientzero.py
> +                if random_collect_episode_num>0:  # random collect
done

2023-07-17 11:50 UTC, jayyoung0802 commented on lzero/policy/muzero.py
> +                    action_index_in_legal_action_set, visit_count_distribution_entropy = select_action(
done

2023-07-17 11:57 UTC, jayyoung0802 commented on zoo/atari/config/atari_efficientzero_config.py
> +random_collect_episode_num=0
done

2023-07-25 04:03 UTC, puyuan1996 requested changes

2023-07-25 04:03 UTC, puyuan1996 commented on lzero/policy/muzero.py
> +            eps_greedy_exploration_in_collect=False,
注释统一写在变量的上面一行

2023-07-25 04:03 UTC, puyuan1996 commented on zoo/atari/config/atari_efficientzero_config.py
> +            # need to be tuned
need to be tuned 扩充为需要根据环境和算法的特点动态调整decay的步数

2023-07-25 04:03 UTC, puyuan1996 commented on zoo/atari/config/atari_efficientzero_config.py
> +eps_greedy_exploration_in_collect = False
random_collect_episode_num直接在下面写定为0, eps_greedy_exploration_in_collect变量按现在的保留，因为random_collect原理上存在一定问题，性能还不太好。

2023-07-25 09:24 UTC, jayyoung0802 commented on lzero/entry/train_muzero.py
> +    # Accumulate plenty of data at the beginning of training.
done!

2023-07-25 09:25 UTC, jayyoung0802 commented on lzero/entry/train_muzero.py
> +        # reset the random_collect_episode_num to 0
无需重置为0，代码冗余

2023-07-25 09:26 UTC, jayyoung0802 commented on lzero/policy/random_policy.py
> +        The policy class for EfficientZero.
done

2023-07-25 09:26 UTC, jayyoung0802 commented on lzero/policy/random_policy.py
> +        ready_env_id=None
done

2023-07-25 09:28 UTC, jayyoung0802 commented on lzero/policy/random_policy.py
> +                # NOTE: The action is randomly selected from the legal action set, the distribution is the real visit count distribution from the MCTS seraech.
done

2023-07-25 09:29 UTC, jayyoung0802 commented on lzero/policy/random_policy.py
> +                # random action
done

2023-07-25 09:30 UTC, jayyoung0802 commented on lzero/policy/muzero.py
> +            eps_greedy_exploration_in_collect=False,
done

2023-07-25 09:32 UTC, jayyoung0802 commented on zoo/atari/config/atari_efficientzero_config.py
> +            # need to be tuned
done

2023-07-25 09:32 UTC, jayyoung0802 commented on zoo/atari/config/atari_efficientzero_config.py
> +eps_greedy_exploration_in_collect = False
done

2023-07-26 02:54 UTC, puyuan1996 commented on lzero/policy/efficientzero.py
> +            # (bool) Whether to use eps greedy exploration in collecting data.
这里没有改

2023-07-26 02:56 UTC, puyuan1996 commented on lzero/policy/random_policy.py
> +                action = int(np.random.choice(legal_actions[env_id], 1))
变量名 action 改成 random_action, 下面传入给dict的也是

2023-07-26 03:11 UTC, puyuan1996 commented on lzero/entry/train_muzero.py
> +    # Comparing Baselines: The performance of an agent when acting randomly can serve as a baseline for evaluating the effectiveness of RL algorithms.
这里用gpt4润色一下，感觉不是很通顺

2023-07-26 03:11 UTC, puyuan1996 commented on zoo/atari/config/atari_efficientzero_config.py
> +            # according to the characteristics of the environment and the algorithm
使用完整的句子，用gpt4润色一下

2023-07-26 07:05 UTC, jayyoung0802 commented on lzero/policy/efficientzero.py
> +            # (bool) Whether to use eps greedy exploration in collecting data.
done

2023-07-26 07:07 UTC, jayyoung0802 commented on lzero/policy/random_policy.py
> +                action = int(np.random.choice(legal_actions[env_id], 1))
done

2023-07-26 07:20 UTC, jayyoung0802 commented on lzero/entry/train_muzero.py
> +    # Comparing Baselines: The performance of an agent when acting randomly can serve as a baseline for evaluating the effectiveness of RL algorithms.
done

2023-07-26 07:37 UTC, jayyoung0802 commented on zoo/atari/config/atari_efficientzero_config.py
> +            # according to the characteristics of the environment and the algorithm
done

2023-08-01 09:29 UTC, PaParaZz1 approved these changes

2023-08-01 09:29 UTC, merged