doc(xcy): mcts_comment
opendilab/LightZero pull request #57
Opened 2023-07-27 03:39 UTC by HarryXuancy

2023-07-27 07:14 UTC, puyuan1996 requested changes

2023-07-27 07:14 UTC, puyuan1996 commented on zoo/board_games/mcts_bot.py
> +            - parent(): The parent node of current node. It is used for backpropagation. For the root node, this parameter is None.
- parent (:obj:`MCTSNode`):  This parent node of the current node. The parent node is primarily used for backpropagation during the Monte Carlo Tree Search. For the root node, this parent returns None as it does not have a parent node.

2023-07-27 07:14 UTC, puyuan1996 commented on zoo/board_games/mcts_bot.py
> +        """
```
This method checks if the node is fully expanded. A node is considered fully expanded when all of its child nodes have been selected at least once. 

Whenever a new child node is selected for the first time, a corresponding action is removed from the list of legal actions. Once the list of legal actions is depleted, it signifies that all child nodes have been selected, thereby indicating that the parent node is fully expanded.
```

2023-07-27 07:14 UTC, puyuan1996 commented on zoo/board_games/mcts_bot.py
>          '''
使用"""

2023-07-27 07:14 UTC, puyuan1996 commented on zoo/board_games/mcts_bot.py
> +        # randomly choose an action
Overview:
            This method implements the rollout policy for a node during the Monte Carlo Tree Search.
            The rollout policy is used to determine the action taken during the simulation phase of the MCTS. In this case, the policy is to randomly choose an action from the list of possible actions.
        Arguments:
            - possible_actions: A list of all possible actions that can be taken from the current state.
        Return: 
            A randomly chosen action from the list of possible actions.

2023-07-27 07:46 UTC, puyuan1996 requested changes

2023-07-27 07:46 UTC, puyuan1996 commented on zoo/board_games/mcts_bot.py
> +        The subclass, which inherits from the abstract base class, implements the specific methods required for a MCTS node.
for a TwoPlayers *

2023-07-27 07:46 UTC, puyuan1996 commented on zoo/board_games/mcts_bot.py
> +    # 为什么不直接在initialize里定义啊？？？？？？？？？？？？？？？？？？？？？？？？？
可以改到__init__里面去哈

2023-07-27 07:46 UTC, puyuan1996 commented on zoo/board_games/mcts_bot.py
>          '''
统一注释格式"""

2023-07-27 07:46 UTC, puyuan1996 commented on zoo/board_games/mcts_bot.py
>      @property
整个方法优化为：    
```
@property
    def q(self):
        """
        This property represents the estimated value (Q-value) of the current node.

        self._results[1] represents the number of wins for player 1.
        self._results[-1] represents the number of wins for player 2.

        The Q-value is calculated depends on which player is the current player at the parent node,
        and is computed as the difference between the wins of the current player and the opponent.
        If the parent's current player is player 1, Q-value is the difference of player 1's wins and player 2's wins.
        If the parent's current player is player 2, Q-value is the difference of player 2's wins and player 1's wins.

        For example, if self._results[1] = 10 (player 1's wins) and self._results[-1] = 5 (player 2's wins):
        - If the parent's current player is player 1, then Q-value = 10 - 5 = 5.
        - If the parent's current player is player 2, then Q-value = 5 - 10 = -5.

        This way, a higher Q-value for a node indicates a higher win rate for the parent's current player.
        """

        # Determine the number of wins and losses based on the current player at the parent node.
        wins, loses = (self._results[1], self._results[-1]) if self.parent.env.current_player == 1 else (
        self._results[-1], self._results[1])

        # Calculate and return the Q-value as the difference between wins and losses.
        return wins - loses
```

2023-07-27 07:46 UTC, puyuan1996 commented on zoo/board_games/mcts_bot.py
> +            reward (int):
按DI-engine的注释格式，参考[这里](https://github.com/opendilab/DI-engine/blob/main/ding/model/common/head.py)：- reward (:obj:`int`):

2023-07-27 07:46 UTC, puyuan1996 commented on zoo/board_games/mcts_bot.py
>          return self._number_of_visits
"""
    This property represents the number of times the node has been visited during the search.
    """

2023-07-27 07:46 UTC, puyuan1996 commented on zoo/board_games/mcts_bot.py
>      def expand(self):
```
   """
    Overview:
        This method expands the current node by creating a new child node.

        It pops an action from the list of legal actions, simulates the action to get the next game state,
        and creates a new child node with that state. The new child node is then added to the list of children nodes.
    """
```

2023-07-27 07:46 UTC, puyuan1996 commented on zoo/board_games/mcts_bot.py
>      def is_terminal_node(self):
```
    """
    Overview:
        This method checks if the current node is a terminal node.

        It uses the game environment's get_done_reward method to check if the game has ended.
    """
```

2023-07-27 07:46 UTC, puyuan1996 commented on zoo/board_games/mcts_bot.py
> +            Take action according to the rollout policy, such as random policy.
"""
    This method performs a rollout (simulation) from the current node.

    It repeatedly selects an action based on the rollout policy and simulates the action until the game ends.
    The method then returns the reward of the game's final state.
    """

2023-07-27 07:46 UTC, puyuan1996 commented on zoo/board_games/mcts_bot.py
>      def backpropagate(self, result):
"""
    This method performs backpropagation from the current node.

    It increments the number of times the node has been visited and the number of wins for the result.
    If the current node has a parent, the method recursively backpropagates the result to the parent.
    """

2023-07-27 07:46 UTC, puyuan1996 commented on zoo/board_games/mcts_bot.py
>          """
"""
          Implement the tree policy for action selection during rollout.

          At each step, if the current node is not fully expanded, it expands.
          If it is fully expanded, it moves to the best child according to the tree policy.
          This continues until a terminal node is reached, which is then returned.

          Returns:
              The terminal node reached by following the tree policy.
          """

2023-07-27 07:46 UTC, puyuan1996 commented on zoo/board_games/mcts_bot.py
>              assert (total_simulation_seconds is not None)
# If no simulations number is provided, run simulations for the specified time

2023-07-27 07:46 UTC, puyuan1996 commented on zoo/board_games/mcts_bot.py
>          else:
# If simulations number is provided, run the specified number of simulations

2023-07-27 07:50 UTC, puyuan1996 requested changes

2023-07-27 07:50 UTC, puyuan1996 commented on zoo/board_games/mcts_bot.py
>  class MCTSSearchNode(object):
class名称改为MCTSSearch

2023-07-27 07:50 UTC, puyuan1996 commented on zoo/board_games/mcts_bot.py
> +    """
"""
         Initialize the Monte Carlo Tree Search Bot.

         Arguments:
             - ENV: The environment in which the MCTS bot operates.
             - cfg: Configuration parameters for the bot.
             - bot_name (str): The name of the bot.
             - num_simulation (int): Number of simulations to perform for each move. Default is 10000.
         """

2023-07-27 07:50 UTC, puyuan1996 commented on zoo/board_games/mcts_bot.py
>      def get_actions(self, state, player_index):
"""
         Get the best action for a given game state.

         A new environment is created for simulations. The environment is reset to the given state.
         Then, MCTS is performed with the specified number of simulations to find the best action.

         Arguments:
             - state: The current game state.
             - player_index (int): The index of the current player.

         Returns:
             The best action determined by MCTS.
         """

2023-07-27 07:53 UTC, puyuan1996 commented on zoo/board_games/mcts_bot.py
>          simulator_env = self.ENV(EasyDict(self.cfg))
确实应该在初始化中执行这一行哈，这里应该是之前写成了，你改好所有的后，在执行mcts_bot的测试文件哈

2023-07-28 07:50 UTC, HarryXuancy commented on zoo/board_games/mcts_bot.py
> +    """
已修改，并且在代码开头添加了整个代码的overview

2023-07-28 07:53 UTC, HarryXuancy commented on zoo/board_games/mcts_bot.py
> +                - The methods in this object implement functionalities such as environment transitions and obtaining game results.
已修改

2023-07-28 07:54 UTC, HarryXuancy commented on zoo/board_games/mcts_bot.py
> +            - parent(): The parent node of current node. It is used for backpropagation. For the root node, this parameter is None.
已修改

2023-07-31 02:51 UTC, puyuan1996 commented on lzero/mcts/ptree/ptree_az.py
> +    # 把env作为节点的变量，或者单独分出去，这有没有什么说法
lzero/mcts/ptree/ptree_az.py 按照原来的代码版本取消更改哈，ptree_az.py的注释优化新开一个PR

2023-07-31 07:52 UTC, puyuan1996 commented on zoo/classic_control/cartpole/config/cartpole_muzero_config.py
> +    exp_name=f'data_mz_ctree/cartpole_muzero_ns{num_simulations}_upc{update_per_collect}_rr{reanalyze_ratio}_stopvalue150',
这个文件取消更改哈，可以直接复制原仓库的代码

2023-07-31 07:52 UTC, puyuan1996 commented on zoo/board_games/tictactoe/config/tictactoe_muzero_bot_mode_config.py
> -    train_muzero([main_config, create_config], seed=0, max_env_step=max_env_step)
这个文件取消更改哈，可以直接复制原仓库的代码

2023-07-31 11:41 UTC, puyuan1996 commented on zoo/board_games/mcts_bot.py
> +        Overview
Overview:

2023-07-31 11:43 UTC, puyuan1996 commented on zoo/board_games/test_speed_win-rate_between_bots.py
> +        -num_simulations (:obj:`int`): The number of the simulations required to find the best move.
本文件里面的 `-num_simulations (:obj:`int`):` 替换为 `- num_simulations (:obj:`int`): `

2023-08-01 12:45 UTC, merged