doc(xcy):add comment to ptree_az.py
opendilab/LightZero pull request #61
Opened 2023-08-03 07:13 UTC by HarryXuancy

2023-08-06 15:55 UTC, puyuan1996 requested changes

2023-08-06 15:55 UTC, puyuan1996 commented on lzero/mcts/ptree/ptree_az.py
>              self._parent.update_recursive(-leaf_value, mcts_mode)
注释强调一下`-leaf_value`

2023-08-06 15:55 UTC, puyuan1996 commented on lzero/mcts/ptree/ptree_az.py
>              if action is None:
能进入while循环体，node就不是叶子节点，所以这个if action的分支是没有必要的吧？你实验验证确实是这样 ，可以把这个删除了哈

2023-08-06 15:55 UTC, puyuan1996 commented on lzero/mcts/ptree/ptree_az.py
>              simulate_env.step(action)
这几条没有用到的print语句可以删除了哈

2023-08-06 15:55 UTC, puyuan1996 commented on lzero/mcts/ptree/ptree_az.py
> +        in ``play_with_bot_mode``, the leaf_value is calculated from the perspective of player of player 1.
这个修改错了吧

2023-08-06 15:55 UTC, puyuan1996 commented on lzero/mcts/ptree/ptree_az.py
>              if action in simulate_env.legal_actions:
action_probs_dict已经是只包含legal_actions的概率，则可以去掉这一行哈

2023-08-06 15:55 UTC, puyuan1996 commented on lzero/mcts/ptree/ptree_az.py
>          noise = np.random.gamma(self._root_dirichlet_alpha, 1, len(actions))
换成 dirichlet noise
```
actions = list(node.children.keys())
alpha = [self._root_dirichlet_alpha] * len(actions)
noise = np.random.dirichlet(alpha)
```

2023-08-06 15:55 UTC, puyuan1996 commented on lzero/mcts/ptree/ptree_az.py
> +        # 这边的pb_c的base和init怎么来的没看明白！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！
增加Multi-armed Bandits with Episode Context这篇PUCB论文的链接引用

2023-08-06 15:55 UTC, puyuan1996 commented on lzero/mcts/ptree/ptree_az.py
>              simulate_env_copy = copy.deepcopy(simulate_env)
copy.deepcopy我在这个[分支](https://github.com/opendilab/LightZero/tree/dev-go-league-polish-copy)优化了哈，通过 MCTS __init__传入env，然后这里调用reset函数即可

2023-08-09 04:01 UTC, HarryXuancy commented on lzero/mcts/ptree/ptree_az.py
>              self._parent.update_recursive(-leaf_value, mcts_mode)
overview里有对是否取负值的相应解释，在对应的行加入了补充注释

2023-08-09 10:07 UTC, puyuan1996 requested changes

2023-08-09 10:07 UTC, puyuan1996 commented on lzero/mcts/ptree/ptree_az.py
> +        Initializes the MCTS search process.
Overview应该是阐述这个class的功能。

2023-08-09 10:07 UTC, puyuan1996 commented on lzero/mcts/ptree/ptree_az.py
>      def __init__(self, cfg: EasyDict) -> None:
这里才是 Initializes the MCTS search process.

2023-08-09 10:07 UTC, puyuan1996 commented on lzero/mcts/ptree/ptree_az.py
> +                    # leaf_value = 1 if simulate_env.current_player == winner else -1
这里为什么修改呀

2023-08-09 10:07 UTC, puyuan1996 commented on lzero/mcts/ptree/ptree_az.py
> +            For more details, please refer to this paper: https://link.springer.com/article/10.1007/s10472-011-9258-6
换成这个容易下载的链接吧 http://gauss.ececs.uc.edu/Workshops/isaim2010/papers/rosin.pdf

2023-08-09 12:00 UTC, HarryXuancy commented on lzero/mcts/ptree/ptree_az.py
> +                    # leaf_value = 1 if simulate_env.current_player == winner else -1
我觉得这里是一个判定为done的节点,那么胜利者肯定是上一个玩家，因为上一个玩家下完游戏就结束了，说明他赢了。当前玩家不会==winner，这边我也加断点跑了一下，如果value==1就触发断点，但是没有触发。所以我觉得value应该只会是-1

2023-08-09 12:07 UTC, HarryXuancy commented on lzero/mcts/ptree/ptree_az.py
>          The node base class for tree_search.
已优化

2023-08-09 13:25 UTC, puyuan1996 commented on lzero/mcts/ptree/ptree_az.py
> +                    # leaf_value = 1 if simulate_env.current_player == winner else -1
这个跟游戏规则有关哈，如果是围棋需要2个玩家连续执行pass, 这时游戏才会结束，而胜负2个玩家都有可能哈，所以还是用之前兼容的写法吧

2023-08-09 13:43 UTC, merged